### ISSUE TITLE
why the value is 288 in willow filter?

### ISSUE THREAD

**Issue by realmyth** [kenju/instagram_js_filter#1]
In line 893 of worker.filter.js, is there a mistake ?

  var b = [
    [ 0,   0,  30],
    [ 1,  40,  70],
    [ 2, 112, 165],
    [ 3, 195, 215],
    [ 4, 255, 288]

**Comment by kenju** [comment]
👀

**Comment by kenju** [comment]
👀

**Comment by realmyth** [comment]
not used

**Comment by kenju** [comment]
Fixed. Thanks for reporting.

https://github.com/kenju/instagram_js_filter/blob/master/src/effects/rgb_map.js#L414
